In [ ]:
import multiprocessing

n_workers = multiprocessing.cpu_count()

In [4]:
n_workers

10

In [5]:
import polars as pl
pl.__version__


'1.37.1'

In [7]:
 
df = pl.DataFrame({
    "name": ["Alice", "Bob", "Charlie"],
    "age": [25, 30, 35],
    "salary": [50000, 60000, 70000]
})
 
print(df)

shape: (3, 3)
┌─────────┬─────┬────────┐
│ name    ┆ age ┆ salary │
│ ---     ┆ --- ┆ ---    │
│ str     ┆ i64 ┆ i64    │
╞═════════╪═════╪════════╡
│ Alice   ┆ 25  ┆ 50000  │
│ Bob     ┆ 30  ┆ 60000  │
│ Charlie ┆ 35  ┆ 70000  │
└─────────┴─────┴────────┘


In [1]:
# Source - https://stackoverflow.com/a/61598951
# Posted by Szymon Maszke, modified by community. See post 'Timeline' for change history
# Retrieved 2026-04-16, License - CC BY-SA 4.0

import torch

tensor = torch.tensor([1, 0, 2, 3, 4])
tensor.shape # torch.Size([5])
tensor.unsqueeze(dim=0).shape # [1, 5]
tensor.unsqueeze(dim=1).shape # [5, 1]


torch.Size([5, 1])

In [2]:
tensor = torch.tensor([1, 0, 2, 3, 4])
tensor

tensor([1, 0, 2, 3, 4])

In [3]:
tensor.shape

torch.Size([5])

In [7]:
x = tensor.unsqueeze(dim=0)

x

x

tensor([[1, 0, 2, 3, 4]])

In [8]:
x = tensor.unsqueeze(dim=1)

x

tensor([[1],
        [0],
        [2],
        [3],
        [4]])

In [11]:
x.squeeze(dim=1)
x

tensor([[1],
        [0],
        [2],
        [3],
        [4]])

In [ ]:
import torch
import torch.nn as nn

class MinimalCNN(nn.Module):
    def __init__(self):
        super(MinimalCNN, self).__init__()
        # 1. Define the layers here
        
    def forward(self, x):
        # 2. Define the flow of data (the forward pass)
        return x

In [ ]:
import torch
a = torch.randn(4, 4)
a
torch.tensor([[ 1.3398,  0.2663, -0.2686,  0.2450],
        [-0.7401, -0.8805, -0.3402, -1.1936],
        [ 0.4907, -1.3948, -1.0691, -0.3132],
        [-1.6092,  0.5419, -0.2993,  0.3195]])
torch.argmax(a)


NameError: name 'tensor' is not defined

In [12]:
a = torch.tensor([[ 1.3398,  0.2663, -0.2686,  0.2450],
        [-0.7401, -0.8805, -0.3402, -1.1936],
        [ 0.4907, -1.3948, -1.0691, -0.3132],
        [-1.6092,  0.5419, -0.2993,  0.3195]])

parg = torch.argmax(a, dim=1)
print("argmax:", parg)
print()
pmax = torch.max(a, dim=1)
print("max:", pmax)


argmax: tensor([0, 2, 0, 1])

max: torch.return_types.max(
values=tensor([ 1.3398, -0.3402,  0.4907,  0.5419]),
indices=tensor([0, 2, 0, 1]))


In [ ]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("cheddad/miniddsm2")

print("Path to dataset files:", path)

100%|██████████| 49.1G/49.1G [1:31:12<00:00, 9.63MB/s]

Extracting files...
